### ISSUE TITLE
Android compatibility warning "StrictMode policy violation"

### ISSUE THREAD

**Issue by dimondl** [AppsFlyerSDK/appsflyer-unity-plugin#17]
After update sdk to version 5.1.1 and (also for 5.3.0) we got Android compatibility warnings in google play console  Pre-launch reports. 

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ldalvik/system/BaseDexClassLoader;->pathList:Ldalvik/system/DexPathList;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Native Method)
	at com.appsflyer.internal.a.<clinit>(:3708)
	at com.appsflyer.internal.a.ǃ(Unknown Source:0)
	at com.appsflyer.AppsFlyerLibCore$c.run(:3343)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.appsflyer.AFExecutor$1$3.run(:31)
	at java.lang.Thread.run(Thread.java:919)
```
```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ldalvik/system/DexPathList;->nativeLibraryDirectories:Ljava/util/List;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Native Method)
	at com.appsflyer.internal.a.<clinit>(:3714)
	at com.appsflyer.internal.a.ǃ(Unknown Source:0)
	at com.appsflyer.AppsFlyerLibCore$c.run(:3343)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.appsflyer.AFExecutor$1$3.run(:31)
	at java.lang.Thread.run(Thread.java:919)
```

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ldalvik/system/DexPathList;->nativeLibraryPathElements:[Ldalvik/system/DexPathList$NativeLibraryElement;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Native Method)
	at com.appsflyer.internal.a.<clinit>(:3717)
	at com.appsflyer.internal.a.ǃ(Unknown Source:0)
	at com.appsflyer.AppsFlyerLibCore$c.run(:3343)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.appsflyer.AFExecutor$1$3.run(:31)
	at java.lang.Thread.run(Thread.java:919)
```

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/app/ActivityThread;->currentApplication()Landroid/app/Application;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
	at java.lang.Class.getMethod(Class.java:2066)
	at java.lang.Class.getMethod(Class.java:1693)
	at com.appsflyer.internal.a.<clinit>(:1773)
	at com.appsflyer.internal.a.ǃ(Unknown Source:0)
	at com.appsflyer.AppsFlyerLibCore$c.run(:3343)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.appsflyer.AFExecutor$1$3.run(:31)
	at java.lang.Thread.run(Thread.java:919)
```

Regards,
Dmitry

**Comment by wesfieldj** [comment]
@dimondl Thanks for reporting this issue.

We are investigating this internally. 

We will update you when we have something. 

Thanks!

**Comment by af-fess** [comment]
This is related to new restrictions as part of Android 9.
https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces

In some cases we use reflection that light greylisted. FOr example:

```
 Class.forName("android.os.SystemProperties")
                    .getMethod("get", String.class).invoke(null, key)
```
