### ISSUE TITLE
Android, v5 EDM4U - ClassNotFoundException: com.bun.miitmdid.core.JLibrary

### ISSUE THREAD

**Issue by Bogdan-sybo** [AppsFlyerSDK/appsflyer-unity-plugin#30]
After adding the latest SDK(v5 using EDM4U) I get the following error after every launched AppsFlyer event.
```
I/AppsFlyerOaid5.4.0: Fetch
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bun/miitmdid/core/JLibrary;
        at com.appsflyer.oaid.OaidClient.fetchMsa(OaidClient.java:76)
        at com.appsflyer.oaid.OaidClient.fetch(OaidClient.java:64)
        at com.appsflyer.AppsFlyerLibCore.ɩ(:50602)
        at com.appsflyer.AppsFlyerLibCore.Ι(:1603)
        at com.appsflyer.AppsFlyerLibCore.ι(:99)
        at com.appsflyer.AppsFlyerLibCore$e.run(:3307)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.appsflyer.AFExecutor$1$1.run(:31)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bun.miitmdid.core.JLibrary" on path: DexPathList
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.appsflyer.oaid.OaidClient.fetchMsa(OaidClient.java:76) 
        at com.appsflyer.oaid.OaidClient.fetch(OaidClient.java:64) 
        at com.appsflyer.AppsFlyerLibCore.ɩ(:50602) 
        at com.appsflyer.AppsFlyerLibCore.Ι(:1603) 
        at com.appsflyer.AppsFlyerLibCore.ι(:99) 
        at com.appsflyer.AppsFlyerLibCore$e.run(:3307) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at com.appsflyer.AFExecutor$1$1.run(:31) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by af-vs** [comment]
Hi @Bogdan-sybo!

This is an expected exception if you don't aim to collect OAID (device identifier for China market. You can read more about it here)

We understand that the full stack trace may look concerning and stopped printing it in the latest version 5.4.3. As soon as Unity plugin v5.4.3 is released you can update and will no longer get this in the logs.
