### ISSUE TITLE
Unity SDK v6: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bun/miitmdid/core/JLibrary

### ISSUE THREAD

**Issue by bilck** [AppsFlyerSDK/appsflyer-unity-plugin#35]
Hello, we have just tried upgrading our AppsFlyer SDK to v6.0.1_beta and got the following errors:

```2020/08/24 12:56:24.979 14843 15002 Error AppsFlyer_5.4.1 ac
2020/08/24 12:56:24.979 14843 15002 Error AppsFlyer_5.4.1 java.util.concurrent.TimeoutException
2020/08/24 12:56:24.979 14843 15002 Error AppsFlyer_5.4.1 	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
2020/08/24 12:56:24.979 14843 15002 Error AppsFlyer_5.4.1 	at com.appsflyer.internal.ContentFetcher.get(:45)
2020/08/24 12:56:24.979 14843 15002 Error AppsFlyer_5.4.1 	at com.appsflyer.internal.ac.ɩ(:22)
2020/08/24 12:56:24.979 14843 15002 Error AppsFlyer_5.4.1 	at com.appsflyer.AppsFlyerLibCore.getAttributionId(:2872)
2020/08/24 12:56:24.979 14843 15002 Error AppsFlyer_5.4.1 	at com.appsflyer.AppsFlyerLibCore.ɩ(:1964)
2020/08/24 12:56:24.979 14843 15002 Error AppsFlyer_5.4.1 	at com.appsflyer.AppsFlyerLibCore.Ι(:1603)
2020/08/24 12:56:24.979 14843 15002 Error AppsFlyer_5.4.1 	at com.appsflyer.AppsFlyerLibCore.ι(:99)
2020/08/24 12:56:24.979 14843 15002 Error AppsFlyer_5.4.1 	at com.appsflyer.AppsFlyerLibCore$e.run(:3307)
2020/08/24 12:56:24.979 14843 15002 Error AppsFlyer_5.4.1 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
2020/08/24 12:56:24.979 14843 15002 Error AppsFlyer_5.4.1 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020/08/24 12:56:24.979 14843 15002 Error AppsFlyer_5.4.1 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2020/08/24 12:56:24.979 14843 15002 Error AppsFlyer_5.4.1 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020/08/24 12:56:24.979 14843 15002 Error AppsFlyer_5.4.1 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020/08/24 12:56:24.979 14843 15002 Error AppsFlyer_5.4.1 	at com.appsflyer.AFExecutor$1$1.run(:31)
2020/08/24 12:56:24.979 14843 15002 Error AppsFlyer_5.4.1 	at java.lang.Thread.run(Thread.java:764)
2020/08/24 12:56:24.984 14843 15002 Info AppsFlyer_5.4.1 IMEI was not collected.
2020/08/24 12:56:24.987 14843 15002 Info AppsFlyer_5.4.1 Android ID was not collected.
2020/08/24 12:56:24.993 14843 15002 Info AppsFlyerOaid5.4.0 Fetch
2020/08/24 12:56:24.993 14843 15002 Info AppsFlyerOaid5.4.0 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bun/miitmdid/core/JLibrary;
2020/08/24 12:56:24.993 14843 15002 Info AppsFlyerOaid5.4.0 	at com.appsflyer.oaid.OaidClient.fetchMsa(OaidClient.java:76)
2020/08/24 12:56:24.993 14843 15002 Info AppsFlyerOaid5.4.0 	at com.appsflyer.oaid.OaidClient.fetch(OaidClient.java:64)
2020/08/24 12:56:24.993 14843 15002 Info AppsFlyerOaid5.4.0 	at com.appsflyer.AppsFlyerLibCore.ɩ(:50602)
2020/08/24 12:56:24.993 14843 15002 Info AppsFlyerOaid5.4.0 	at com.appsflyer.AppsFlyerLibCore.Ι(:1603)
2020/08/24 12:56:24.993 14843 15002 Info AppsFlyerOaid5.4.0 	at com.appsflyer.AppsFlyerLibCore.ι(:99)
2020/08/24 12:56:24.993 14843 15002 Info AppsFlyerOaid5.4.0 	at com.appsflyer.AppsFlyerLibCore$e.run(:3307)
2020/08/24 12:56:24.993 14843 15002 Info AppsFlyerOaid5.4.0 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
2020/08/24 12:56:24.993 14843 15002 Info AppsFlyerOaid5.4.0 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020/08/24 12:56:24.993 14843 15002 Info AppsFlyerOaid5.4.0 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2020/08/24 12:56:24.993 14843 15002 Info AppsFlyerOaid5.4.0 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020/08/24 12:56:24.993 14843 15002 Info AppsFlyerOaid5.4.0 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020/08/24 12:56:24.993 14843 15002 Info AppsFlyerOaid5.4.0 	at com.appsflyer.AFExecutor$1$1.run(:31)
2020/08/24 12:56:24.993 14843 15002 Info AppsFlyerOaid5.4.0 	at java.lang.Thread.run(Thread.java:764)
2020/08/24 12:56:24.993 14843 15002 Info AppsFlyerOaid5.4.0 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bun.miitmdid.core.JLibrary" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.plotkids.monicatv-rPIwGPmx8v6LtE2wJcsW8w==/base.apk"],nativeLibraryDirectories=[/data/app/com.plotkids.monicatv-rPIwGPmx8v6LtE2wJcsW8w==/lib/arm64, /data/app/com.plotkids.monicatv-rPIwGPmx8v6LtE2wJcsW8w==/base.apk!/lib/arm64-v8a, /system/lib64]]
2020/08/24 12:56:24.993 14843 15002 Info AppsFlyerOaid5.4.0 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
2020/08/24 12:56:24.993 14843 15002 Info AppsFlyerOaid5.4.0 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2020/08/24 12:56:24.993 14843 15002 Info AppsFlyerOaid5.4.0 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2020/08/24 12:56:24.993 14843 15002 Info AppsFlyerOaid5.4.0 	... 13 more
2020/08/24 12:56:25.009 14843 15002 Info AppsFlyer_5.4.1 AppsFlyer: first launch date: 2020-08-24_145541+0000
2020/08/24 12:56:25.016 14843 15002 Warn AppsFlyer_5.4.1 Cannot verify existence of our InstanceID Listener Service in the manifest. Please refer to documentation.
2020/08/24 12:56:25.018 14843 15002 Debug AppsFlyer_5.4.1 didConfigureTokenRefreshService=false
2020/08/24 12:56:25.023 14843 15002 Debug AppsFlyer_5.4.1 No deep link detected
```

We have tried adding `-keep class com.bun.miitmdid.** { *; }` to our proguard-user.txt file but it didn't work.

**Comment by bilck** [comment]
According to [this post](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/issues/30), _"This is an expected exception if you don't aim to collect OAID (device identifier for China market. You can read more about it [here](https://support.appsflyer.com/hc/en-us/articles/360003084578-Bulletin-Open-Advertiser-ID-OAID-in-AppsFlyer-Android-SDK))"_.

Is it the same case?

Apparently it's working, but not without throwing some scary errors:
```2020/08/24 20:33:49.341 21842 23737 Info AppsFlyer_5.4.1 sendTrackingWithEvent from activity: android.app.Application
2020/08/24 20:33:49.342 21842 23737 Info AppsFlyer_5.4.1 Trying to fetch GAID..
2020/08/24 20:33:49.425 21842 23737 Info AppsFlyer_5.4.1 ******* sendTrackingWithEvent: ScreenVisit
2020/08/24 20:33:49.438 21842 23781 Debug OpenSSLLib OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
2020/08/24 20:33:49.480 21842 23737 Info AppsFlyer_5.4.1 IMEI was not collected.
2020/08/24 20:33:49.484 21842 23737 Info AppsFlyer_5.4.1 Android ID was not collected.
2020/08/24 20:33:49.489 21842 23737 Info AppsFlyerOaid5.4.0 Fetch
2020/08/24 20:33:49.489 21842 23737 Info AppsFlyerOaid5.4.0 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bun/miitmdid/core/JLibrary;
2020/08/24 20:33:49.489 21842 23737 Info AppsFlyerOaid5.4.0 	at com.appsflyer.oaid.OaidClient.fetchMsa(Unknown Source:7)
2020/08/24 20:33:49.489 21842 23737 Info AppsFlyerOaid5.4.0 	at com.appsflyer.oaid.OaidClient.fetch(Unknown Source:15)
2020/08/24 20:33:49.489 21842 23737 Info AppsFlyerOaid5.4.0 	at com.appsflyer.AppsFlyerLibCore.ɩ(Unknown Source:1719)
2020/08/24 20:33:49.489 21842 23737 Info AppsFlyerOaid5.4.0 	at com.appsflyer.AppsFlyerLibCore.Ι(Unknown Source:69)
2020/08/24 20:33:49.489 21842 23737 Info AppsFlyerOaid5.4.0 	at com.appsflyer.AppsFlyerLibCore.ι(Unknown Source:0)
2020/08/24 20:33:49.489 21842 23737 Info AppsFlyerOaid5.4.0 	at com.appsflyer.AppsFlyerLibCore$e.run(Unknown Source:14)
2020/08/24 20:33:49.489 21842 23737 Info AppsFlyerOaid5.4.0 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
2020/08/24 20:33:49.489 21842 23737 Info AppsFlyerOaid5.4.0 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020/08/24 20:33:49.489 21842 23737 Info AppsFlyerOaid5.4.0 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2020/08/24 20:33:49.489 21842 23737 Info AppsFlyerOaid5.4.0 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020/08/24 20:33:49.489 21842 23737 Info AppsFlyerOaid5.4.0 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020/08/24 20:33:49.489 21842 23737 Info AppsFlyerOaid5.4.0 	at com.appsflyer.AFExecutor$1$1.run(Unknown Source:11)
2020/08/24 20:33:49.489 21842 23737 Info AppsFlyerOaid5.4.0 	at java.lang.Thread.run(Thread.java:764)
2020/08/24 20:33:49.489 21842 23737 Info AppsFlyerOaid5.4.0 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bun.miitmdid.core.JLibrary" on path: DexPathList[[zip file "/data/app/com.explot.gouda-qWXV9C3CHRxvEHMa1cX_iA==/base.apk"],nativeLibraryDirectories=[/data/app/com.explot.gouda-qWXV9C3CHRxvEHMa1cX_iA==/lib/arm64, /data/app/com.explot.gouda-qWXV9C3CHRxvEHMa1cX_iA==/base.apk!/lib/arm64-v8a, /system/lib64]]
2020/08/24 20:33:49.489 21842 23737 Info AppsFlyerOaid5.4.0 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
2020/08/24 20:33:49.489 21842 23737 Info AppsFlyerOaid5.4.0 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2020/08/24 20:33:49.489 21842 23737 Info AppsFlyerOaid5.4.0 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2020/08/24 20:33:49.489 21842 23737 Info AppsFlyerOaid5.4.0 	... 13 more
2020/08/24 20:33:49.498 21842 23737 Info AppsFlyer_5.4.1 AppsFlyer: first launch date: 2020-08-24_211734+0000
2020/08/24 20:33:49.500 21842 23737 Warn AppsFlyer_5.4.1 Cannot verify existence of our InstanceID Listener Service in the manifest. Please refer to documentation.
2020/08/24 20:33:49.501 21842 23737 Debug AppsFlyer_5.4.1 didConfigureTokenRefreshService=false
2020/08/24 20:33:49.524 21842 23737 Debug OpenSSLLib OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
2020/08/24 20:33:49.526 21842 23737 Info AppsFlyer_5.4.1 AppsFlyerLib.sendTrackingWithEvent
2020/08/24 20:33:49.898 21842 23737 Info AppsFlyer_5.4.1 url: https://inapps.appsflyer.com/api/v5.4/androidevent?app_id=com.explot.gouda&buildnumber=5.4.1
2020/08/24 20:33:49.899 21842 23737 Info AppsFlyer_5.4.1 data: {"country":"GB","af_timestamp":"1598312029364","appsflyerKey":"h********************g","isFirstCall":"false","registeredUninstall":true,"operator":"Vivo","isGaidWithGps":"true","app_version_code":"32","eventName":"ScreenVisit","model":"Redmi Note 8 Pro","brand":"Redmi","deviceType":"user","deviceData":{"cpu_abi":"arm64-v8a","build_display_id":"PPR1.180610.011","dim":{"size":"2","ydp":"394.716","xdp":"394.716","y_px":"1080","x_px":"2134","d_dpi":"440"},"arch":"","cpu_abi2":""},"disk":"45715\/112690","sdk":"28","fb":"e8306695-57e6-450c-87b3-6d1e4ecfa3a5","app_version_name":"1.2.1","device":"begonia","cksm_v1":"615f3ce358424e070fb02da31e034f97cd","af_events_api":"1","cell":{"mnc":6,"mcc":724},"network":"WIFI","af_v2":"8455ca7871f1f4f0fdc1d85abbf12d931076b66c","sig":"FE95631CE974B056DADBA327CA31601D1AD7144265E9619F396EAFB7EC4537B9","uid":"1598303851363-8622508576438548166","eventValue":"{\"ScreenName\":\"UI_ParentalGuide-Tab_TeachingStoriesTabContent_Group\",\"PreviousScreenName\":\"UI_ParentalGuide-Tab_WelcomeTabContent_Group\",\"TimeElapsedOnLastScreen\":\"16.60291\"}","lang_code":"en","installDate":"2020-08-24_211141+0000","firstLaunchDate":"2020-08-24_211734+0000","ivc":false,"lang":"English","kef546b":"e874b8cb461ad0d748191e1a0c531a0d5919130d5a1f13","last_boot_time":1596840966760,"sdkExtension":"unity_android_5.4.2","product":"begonia","installer_package":"com.google.android.packageinstaller","date2":"2020-08-24_202208-0300","counter":"2","date1":"2020-08-24_181141-0300","advertiserId":"6aa43438-86d6-4e75-b7e2-7a1d9ee44c3f","advertiserIdEnabled":"true","af_v":"394c29b7138a2d6607c6f54c72414b1167ae42bc","carrier":"VIVO","sensors":{"mm":{"v":[[33.4,-4.5],[-3.4,0.4]],"n":"akm09918c_magnetic"},"gs":{"v":[[0.1,0,0],[-0.1,0,0]],"n":"GYROSCOPE"},"am":{"v":[[8.8,2.2,4.3],[-0.1,0.1,-0.5]],"n":"ACCELEROMETER"}},"af_preinstalled":"false","iaecounter":"40","sc_o":"l","tokenRefreshConfigured":false,"prev_event":"{\"prev_event_timestamp\":\"1598312013372\",\"prev_event_value\":\"{\\\"ScreenName\\\":\\\"UI_ParentalGuide-Tab_WelcomeTabContent_Group\\\",\\\"PreviousScreenName\\\":\\\"UI_ParentalGuide\\\",\\\"TimeElapsedOnLastScreen\\\":\\\"0.01019287\\\"}\",\"prev_event_name\":\"ScreenVisit\"}","platformextension":"android_unity"}
2020/08/24 20:33:49.901 21842 23737 Warn System ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
2020/08/24 20:33:49.902 21842 23737 Info System.out e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
2020/08/24 20:33:49.905 21842 23737 Warn System ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
2020/08/24 20:33:49.906 21842 23737 Info System.out [OkHttp] sendRequest<<
2020/08/24 20:33:50.009 21842 21982 Info AudioTrack isLongTimeZoreData zoer date time 17 Seconds
2020/08/24 20:33:50.151 21842 23737 Info AppsFlyer_5.4.1 response code: 200
```

**Comment by wesfieldj** [comment]
@bilck 

The linked issue has the correct details.

These warnings are nothing to worry about and they will be removed in the next release.

We can see from the logs that the SDK is working properly. 

In the next update, the warnings will no longer be there.

Thanks.
